### ISSUE TITLE
Update() is broken as of 3.4.3

### ISSUE THREAD

**Issue by alertedsnake** [cdgriffith/Box#105]
Given this sample code:
```
import box

if __name__ == '__main__':
    b = box.Box({
        'one': {
            'sub1': 'monkey',
            'sub2': 'goat',
        }
    }, box_it_up = True)

    print(f'box: {b}')
    print(f'one is a {type(b.one)}')
    print(f'expect monkey: {b.one.sub1}')
    print(f'expect goat: {b.one.sub2}')
            
    b.update({'one': {'sub2': 'alpaca'}})
    print(f'one is a {type(b.one)}')
    print(f'expect monkey: {b.one.sub1}')
    print(f'expect alpaca: {b.one.sub2}')
```

It works with < 3.4.3:
```
box: {'one': {'sub1': 'monkey', 'sub2': 'goat'}}
one is a <class 'box.Box'>
expect monkey: monkey
expect goat: goat
one is a <class 'box.Box'>
expect monkey: monkey
expect alpaca: alpaca
```

 But using >= 3.4.3, this is the result:
```
box: {'one': {'sub1': 'monkey', 'sub2': 'goat'}}
one is a <class 'box.Box'>
expect monkey: monkey
expect goat: goat
one is a <class 'dict'>
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    print(f'expect monkey: {b.one.sub1}')
AttributeError: 'dict' object has no attribute 'sub1'
```
I notice there were changes to the `update()` method.

(edited: added some code to print out the types, which show the difference)

**Comment by cdgriffith** [comment]
Thanks for the report! Always appreciate sample code! 

It is an issue with not forcing conversion of sub dictionaries on update, prepping PR.

**Comment by alertedsnake** [comment]
Thanks!  It actually took me about an hour to dig in enough to find the cause - we subclass Box with a bunch of extra logic, so there were a lot of places it could have been.

**Comment by cdgriffith** [comment]
If it's not terribly difficult for you to pull development and test that version would be appreciated. (Will push and release later today either way, I think it should be good now but always better to have more eyes.) 

Thanks again for your work to track that down!

**Comment by alertedsnake** [comment]
Not quite - and different now:
```
$ PYTHONPATH=$(pwd) python ./test.py 
box: {'one': {'sub1': 'monkey', 'sub2': 'goat'}}
one is a <class 'box.Box'>
expect monkey: monkey
expect goat: goat
one is a <class 'box.Box'>
Traceback (most recent call last):
  File "/home/michael/work/boxtest/.venv/lib/python3.6/site-packages/box.py", line 424, in __getitem__
    value = super(Box, self).__getitem__(item)
KeyError: 'sub1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/work/boxtest/.venv/lib/python3.6/site-packages/box.py", line 507, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/home/michael/work/boxtest/.venv/lib/python3.6/site-packages/box.py", line 431, in __getitem__
    raise BoxKeyError(str(err))
box.BoxKeyError: "'sub1'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/work/boxtest/.venv/lib/python3.6/site-packages/box.py", line 509, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'Box' object has no attribute 'sub1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    print(f'expect monkey: {b.one.sub1}')
  File "/home/michael/work/boxtest/.venv/lib/python3.6/site-packages/box.py", line 526, in __getattr__
    raise BoxKeyError(str(err))
box.BoxKeyError: "'Box' object has no attribute 'sub1'"
```

**Comment by cdgriffith** [comment]
Ah, that is because you update that entity and the new one does not have that key. `b.update({'one': {'sub2': 'alpaca'}})`

**Comment by alertedsnake** [comment]
Oh! Well that should have been obvious.
I believe you did say that `update` would now work more like it does on `dict`.

I'll change our code which does a deep merge to do this properly rather than rely on Box's `update` to do it for me. 

I saw your other issue about backwards compatibility... Should I point out that this kind of update worked before 3.4.3? :)

Thanks for fixing this so fast!

**Comment by cdgriffith** [comment]
Very good points, when writing the update originally I (obviously) didn't deeply look into how standard dicts operated. And you are totally right I don't want a big change to happen on same major release, so will figure out how to get this all working with the old way of merging! 

Then going forward with 4.x will possible have that as its own function, like `merge_update` or something.

**Comment by alertedsnake** [comment]
I've been here myself, more than once. And I agree that `dict`-like performance is probably the ideal goal. A new function for 4.0 sounds perfect.

I'll be happy to test further, just let me know!

**Comment by cdgriffith** [comment]
Thanks, think I hopefully got everything sorted finally in development now.

**Comment by alertedsnake** [comment]
Hooray:
```
box: {'one': {'sub1': 'monkey', 'sub2': 'goat'}}
one is a <class 'box.Box'>
expect monkey: monkey
expect goat: goat
one is a <class 'box.Box'>
expect monkey: monkey
expect goat: alpaca
```
Looks great!  Thanks for the quick work on this, and for the excellent library!
